/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.deloitte.Assignment;
import org.junit.Test;

public class AssignmentTest {
    @Test
    public void appHasAGreeting() {
        Assignment classUnderTest = new Assignment();
//        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
